version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
cratedelight = true
everycomp = true
pulsetech = true
createsolar = true
farmersdelight = true
create_new_age = true
enchanting_overhauled = true
spectrum = true
nomansland = true
vista = true
create = true
aeronautics = true
immersivepetroleum = true
simulated = true
deep_aether = true
quark = true
dungeonsdelight = true
hexerei = true
stonezone = true
minecraft = true
moreburners = true
rusticdelight = true
comforts = true
chalk = true
sliceanddice = true
appliedcreate = true
bosses_of_mass_destruction = true
immeng = true
blahaj = true
psi = false
aether = true
malum = true
ae2 = true
only_blahaj = true
beautify = true
amendments = true
computercraft = true
via_romana = true
appliedpneumatics = true
moonlight = true
immersiveengineering = true
pneumaticcraft = true
exposure = true
offroad = true
